In [4]:
def save_sparse_csr(filename,array):
    np.savez(filename,data = array.data ,indices=array.indices,
             indptr =array.indptr, shape=array.shape )

def load_sparse_csr(filename):
    loader = np.load(filename)
    return csr_matrix((  loader['data'], loader['indices'], loader['indptr']),
                         shape = loader['shape'])

In [5]:
import pandas as pd
import numpy as np 
from pandas import Series
pd.options.display.max_rows=3000
root_dir = os.path.abspath('../..')
task_dir= os.path.join(root_dir,'user_profile')
data_dir=os.path.join(task_dir,'data')
final_data=os.path.join(data_dir,"final_scrap")

In [6]:
from scipy.sparse import csr_matrix
from scipy.sparse import coo_matrix, vstack, hstack

In [7]:
full=load_sparse_csr(os.path.join(final_data,"sparse_representation_full.npz"))

In [45]:
%reset_selective  

In [50]:
%who_ls

['Series',
 'coo_matrix',
 'csr_matrix',
 'data_dir',
 'final_data',
 'full',
 'hstack',
 'load_sparse_csr',
 'np',
 'pd',
 'root_dir',
 'save_sparse_csr',
 'shuffle',
 'svm',
 'task_dir',
 'vstack']

In [8]:
X=full.toarray()

In [9]:
np.random.shuffle(X)

In [10]:
Y=X[:,-1:]
X=X[:,:-1]

In [11]:
X_validate=X[20000:,:]

Y_validate=Y[20000:]

In [12]:
X=X[:20000,:]
Y=Y[:20000]

In [15]:
Y_validate=np.reshape(Y_validate,(Y_validate.shape[0],))

Y=np.reshape(Y,(Y.shape[0],))

In [20]:
Y[:100]

array([ 0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.])

In [13]:
x_validate=csr_matrix(X_validate)

x=csr_matrix(X)

In [16]:
from sklearn import svm
lin_svc = svm.LinearSVC(C=1.0).fit(x, Y)
lin_svc.score(x_validate,Y_validate)

0.96240000000000003

In [18]:
x_test=load_sparse_csr(os.path.join(final_data,"test_x.npz"))
y_test=load_sparse_csr(os.path.join(final_data,"test_y.npz"))

In [29]:
lin_svc.predict(x_test)[:1000]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [27]:
Y_validate[:1000]

array([ 0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,
        1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0

In [4]:
import numpy as np
X = np.array([[1., 0.], [2., 1.], [0., 0.],[2,3],[4,5]])
y = np.array([0, 1, 2,3,4])

from scipy.sparse import coo_matrix
X_sparse = coo_matrix(X)

from sklearn.utils import shuffle

In [5]:
X, X_sparse, y = shuffle(X, X_sparse, y)

In [6]:
X

array([[ 1.,  0.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 0.,  0.],
       [ 2.,  1.]])

In [7]:
y

array([0, 3, 4, 2, 1])

In [9]:
X_sparse.toarray()

array([[ 1.,  0.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 0.,  0.],
       [ 2.,  1.]])